# Generated by Django 5.0 on 2023-12-09 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appmatricula', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='Matricula_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
